# config.toml
# Command-line arguments will override any settings defined here.

[io]
fps = 30.0 # Force output FPS to 30
source = "data/input.mp4"
output = "outputs/processed_with_viz.mp4"
start_frame = 300
end_frame = 600

[detector]
det = "yolo11l.pt"
conf = 0.4
imgsz = 640
# classes = "0,2" # Example: track only persons (0) and cars (2)

[embedder]
# facebook/dinov3-vitl16-pretrain-lvd1689m: A Large ViT with 300 million parameters.
# facebook/dinov3-vitb16-pretrain-lvd1689m: A Base ViT with 86 million parameters.
# facebook/dinov3-vits16-pretrain-lvd1689m: A Small ViT with 21 million parameters.
# facebook/dinov3-vits16plus-pretrain-lvd1689m: A Small+ ViT with 29 million parameters. 
embed_amp = "fp16"
crop_pad = 0.1
embed_model = "facebook/dinov3-vits16-pretrain-lvd1689m"

[scheduler]
# This forces a new embedding to be computed for every single detection.
force_compute_all = true

# Refresh embeddings less frequently to focus budget on new/lost tracks.
refresh_every = 30
iou_gate = 0.7

[tracker]
# Keep ACTIVE tracks for 1 sec (60 frames @ 60fps) before they become LOST.
max_age = 60
# Keep LOST tracks for 5 sec (300 frames @ 60fps) for Re-ID attempts.
reid_max_age = 300
# Similarity threshold to confirm a Re-ID match.
reid_sim_thresh = 0.65
# Only update a track's reference embedding with confident detections.
conf_min_update = 0.4
conf_high = 0.6
conf_low = 0.15

# --- Re-ID Heuristics ---
# Master switch for motion-based filtering. To disable all motion filtering for
# a global, appearance-only Re-ID search, use the '--no-motion-gate' flag
# or set this to false.
motion_gate = true

# For the first 30 frames a track is lost, the tracker will search for it
# near its predicted position (extrapolated from its last known velocity).
# The search radius grows over time as defined by center_gate_base/slope.
extrapolation_window = 60

# After 'extrapolation_window' frames, the tracker assumes the motion prediction
# is unreliable and switches to a global, appearance-only search for that track.
# --- End of Re-ID Heuristics ---

[viz]
# --- Master switch for the advanced debug view ---
debug_panels = true   # Set to true to enable the panels

# --- Enable all advanced visualizations ---
viz_reasons = true    # Show scheduler reasons on bbox labels
viz_hud = true        # Show the real-time statistics HUD
viz_reid = true       # Show enhanced Re-ID event links

# Show lost tracks as dashed boxes so you can see what the tracker is trying to find.
draw_lost = true
line_thickness = 2
font_scale = 0.5

[system]
# cpu = true # Uncomment to force CPU processing

